var myname = 'Insharah Irfan';
var age = '15 years old...';
var bio = 'Web Development Crash Course';
var message = 'Hello Word...';
window.alert(message);
window.alert(myname);
window.alert(age);
window.alert(bio);
var food = 'P';
var food2 = 'I';
var food3 = 'Z';
var food4 = 'A';
window.alert(food+food2+food3+food3+food4);
window.alert(food+food2+food3+food3);
window.alert(food+food2+food3);
window.alert(food+food2);
window.alert(food);
var emailaddress = ' insharahattariya@gmail.com';
window.alert("My Email Address is " + emailaddress);
var book = 'A Smarter Way To Learn JAVASCRIPT';
window.alert("I am trying to learn from the " + book);
document.write('<h2 data-aos="zoom-in-down">Yah! I can write HTML content through JAVASCRIPT</h2>');
var line = ' ▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬ ';
window.alert(line + 'END');
